development:
  bucket: crazygf
  access_key_id: AKIAIJRBURGF7GY7LRBQ
  secret_access_key: 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
test:
  bucket: crazygf-test
  access_key_id: AKIAIJRBURGF7GY7LRBQ
  secret_access_key: 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
production:
  bucket: crazygf-prod
  access_key_id: AKIAIJRBURGF7GY7LRBQ
  secret_access_key: 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